name: "01_Foundation"

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  Plan_Dev:
    uses: omarinux/pocterraformactions/.github/workflows/az_tf_plan.yml@main
    with:
      path: 01_Foundation                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: vispoc-tstate-rg      ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: vispoctfstate3253    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: actions.tfstate                ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: config-dev.tfvars    ## Terraform TFVARS (Required)
      enable_TFSEC: true                 ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      arm_client_id: ${{ secrets.AZURE_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.AZURE_TENANT_ID }}             ## ARM Tenant ID

  Deploy_Dev:
    needs: Plan_Dev
    uses: omarinux/pocterraformactions/.github/workflows/az_tf_apply.yml@main
    with:
      path: 01_Foundation                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: vispoc-tstate-rg      ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: vispoctfstate3253    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: actions.tfstate                ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      gh_environment: Development        ## GH Environment. Default=null - (Optional)
    secrets:
      arm_client_id: ${{ secrets.AZURE_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.AZURE_TENANT_ID }}             ## ARM Tenant ID

  Plan_Uat:
    uses: omarinux/pocterraformactions/.github/workflows/az_tf_plan.yml@main
    with:
      path: 01_Foundation
      az_resource_group: vispoc-tstate-rg      ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: vispoctfstate3253    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: actions.tfstate                ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: config-uat.tfvars
      enable_TFSEC: true                       
    secrets:
      arm_client_id: ${{ secrets.AZURE_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.AZURE_TENANT_ID }}             ## ARM Tenant ID

  Deploy_Uat:
    needs: [Plan_Uat, Deploy_Dev]
    uses: omarinux/pocterraformactions/.github/workflows/az_tf_apply.yml@main
    with:
      path: 01_Foundation
      az_resource_group: vispoc-tstate-rg      ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: vispoctfstate3253    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: actions.tfstate                ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      gh_environment: UserAcceptanceTesting
    secrets:
      arm_client_id: ${{ secrets.AZURE_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.AZURE_TENANT_ID }}             ## ARM Tenant ID

  Plan_Prod:
    uses: omarinux/pocterraformactions/.github/workflows/az_tf_plan.yml@main
    with:
      path: 01_Foundation
      tf_version: latest
      az_resource_group: vispoc-tstate-rg      ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: vispoctfstate3253    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: actions.tfstate                ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: config-prod.tfvars
      enable_TFSEC: true                          
    secrets:
      arm_client_id: ${{ secrets.AZURE_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.AZURE_TENANT_ID }}             ## ARM Tenant ID

  Deploy_Prod:
    needs: [Plan_Prod, Deploy_Uat]
    uses: omarinux/pocterraformactions/.github/workflows/az_tf_apply.yml@main
    with:
      path: 01_Foundation
      az_resource_group: vispoc-tstate-rg      ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: vispoctfstate3253    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: actions.tfstate                ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      gh_environment: Production
    secrets:
      arm_client_id: ${{ secrets.AZURE_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.AZURE_TENANT_ID }}             ## ARM Tenant ID